# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      -   uses: actions/checkout@v3

      -   name: Setup SSH Keys and known_hosts
          env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: |
              ssh-agent -a $SSH_AUTH_SOCK > /dev/null
              ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      -   name: Some task that fetches dependencies
          env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: ./fetch-deps.sh
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

#      - name: Trigger jenkins job
#        uses: jabbukka/jenkins-trigger@main
#        with:
#          url: ${{ secrets.JENKINS_URL }}
#          job_name: ${{ secrets.JENKINS_JOB }}
#          user_name: ${{ secrets.JENKINS_USER }}
#          api_token: ${{ secrets.JENKINS_TOKEN }}
#          wait: "true"
#          timeout: "1000"
