name: Build testcontainers-keycloak

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          java-package: jdk
          distribution: openjdk
      - run: mvn clean install
